name: Activation

on:
  workflow_dispatch: {}

jobs:
  requestActivationFile:
    name: Request activation file
    runs-on: macos-11
    steps:
      - name: Cache Unity installer
        id: cache-unity-installer
        uses: actions/cache@v2
        with:
          path: Unity.pkg
          key: unity-installer
    
      - name: Download Unity
        if: steps.cache-unity-installer.outputs.cache-hit != 'true'
        run: sudo curl -o Unity.pkg 'http://download.unity3d.com/download_unity/${{ env.CHANGESET }}/MacEditorInstaller/Unity.pkg'
        env:
          # VERSION: 2022.1.0a12
          CHANGESET: 816252c3efbb
    
      - name: Install Unity
        run: sudo installer -dumplog -package Unity.pkg -target /Applications
          
      - name: Generate activation file
        run: sudo /Applications/Unity/Unity.app/Contents/MacOS/Unity -quit -nographics -batchmode -createManualActivationFile -logfile -username <> -password <>
        
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unity_v2022.1.0a12.alf
          path: ./Unity_v2022.1.0a12.alf
