name: Activation

on:
  workflow_dispatch: {}

jobs:
  requestActivationFile:
    name: Request activation file
    runs-on: macos-11
    steps:
      - name: Download Unity
        run: sudo curl -o Unity.pkg 'http://download.unity3d.com/download_unity/${{ env.CHANGESET }}/MacEditorInstaller/Unity.pkg'
        env:
          # VERSION: 2022.1.0a12
          CHANGESET: 816252c3efbb
    
      - name: Install Unity
        run: sudo installer -dumplog -package Unity.pkg -target /Applications
        
      - name: Generate activation file
        run: ${{ env.EDITOR_LOCATION }} -batchmode -createManualActivationFile -logfile
        env:
          EDITOR_LOCATION: /Applications/Unity/Unity.app/Contents/MacOS/Unity
        
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unity_v2022.1.0a12.alf
          path: ./Unity_v2022.1.0a12.alf
