name: Build for target platforms

on:
  push:
    branches:
      - master

jobs:
  buildForTargetPlatforms:
    name: Build
    runs-on: macos-11
    steps:
      - name: Install Unity
        run: sudo installer -dumplog -package http://download.unity3d.com/download_unity/${{ env.CHANGESET }}/MacEditorInstaller/Unity.pkg
        env:
          # 2022.1.0a12
          CHANGESET: 816252c3efbb
